### ISSUE TITLE
Windows openj9-staging failing to compile, merge problem

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk#146]
https://ci.eclipse.org/openj9/job/Build_JDKnext_x86-64_windows_OpenJDK/77
```
22:57:15  c:/Users/jenkins/workspace/Build_JDKnext_x86-64_windows_OpenJDK/src/jdk.jdwp.agent/windows/native/libjdwp/linker_md.c(113): error C2220: warning treated as error - no 'object' file generated
22:57:15  c:/Users/jenkins/workspace/Build_JDKnext_x86-64_windows_OpenJDK/src/jdk.jdwp.agent/windows/native/libjdwp/linker_md.c(113): warning C4028: formal parameter 2 different from declaration
```

openj9 branch is
`dbgsysBuildLibName(char *holder, size_t holderlen, const char *pname, const char *fname)`

while openj9-staging and master branch is
`dbgsysBuildLibName(char *holder, int holderlen, const char *pname, const char *fname)`

**Comment by pshipton** [comment]
@andrew-m-leonard

**Comment by adam-thorpe** [comment]
https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/b35356df4943c21d1e8edfdc2258514b75ada27f#diff-b5078076fd797817acd3d97d9357ceeb
If I remember correctly @pshipton, this change was a change in openjdk code that was fixing a patch we had in openj9. The line above caused a merge conflict when merged from HEAD to openj9-staging.

**Comment by pshipton** [comment]
Problem is the function declaration is inconsistent with the declaration in src/jdk.jdwp.agent/share/native/libjdwp/export/sys.h

openj9-staging
`void    dbgsysBuildLibName(char *, size_t, const char *, const char *);`

master
`void    dbgsysBuildLibName(char *, int, const char *, const char *);`

**Comment by adam-thorpe** [comment]
As part of the patch https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/52226897eb3ce1ba4dee24d518d298125702dee9#diff-2b764b7cc320d5bf9704f09377c94f41 the `src/jdk.jdwp.agent/share/native/libjdwp/export/sys.h` file was edited to compensate for the patch (ie. replacing int to size_t in the above method declaration). In openjdk code, this remained int and when they contributed their change this value was unaffected and therefore was not edited by the auto merge. Clearly me and Andrew missed this when we dealt with the merge conflict, since it was not in conflict itself. So reverting this value back to int as it is in master would effectively remove our patch. Please correct me if I made any mistakes here but this is my understanding of it.

**Comment by pshipton** [comment]
@adam-thorpe sounds good. Please create a PR to fix it, and we'll run some testing to ensure everything still works.

**Comment by adam-thorpe** [comment]
@pshipton can this be closed please?
