### ISSUE TITLE
Re-enable NativeGCM lost due to OpenJDK update 8255557: Decouple GCM from CipherCore

### ISSUE THREAD

**Issue by JasonFengJ9** [ibmruntimes/openj9-openjdk-jdk#323]
`Merge master HEAD into openj9-staging` https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/322 includes `8255557: Decouple GCM from CipherCore` https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/55387a2d979e3fe83e8fbb3f900f013bf4775cbc which moved GCM within `com.sun.crypto.provider.CipherCore` via https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/322/commits/278b6285945177255892ce1f5f6a136bd1f854fd, and effectively removed OpenJ9 JCL patch for `NativeGCM` while `NativeCBC` still stays.

`NativeGCM` implementation requires revisiting and to be re-enabled.

fyi @ashbm5

**Comment by pshipton** [comment]
Created https://github.com/eclipse-openj9/openj9/issues/12896 so we can track this against the jdk17 milestone.

**Comment by ZainabF92** [comment]
PR [#349](https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/349) fixes this issue. I changed NativeGaloisCounterMode to extend CipherSpi instead of FeedbackCipher, overrode the associated abstract methods, and added the inner class GCMEngine (subclasses GCMEncrypt and GCMDecrypt). I also modified SunJCE to allow it to call NativeGaloisCounterMode. I ran the crypto tests using jtreg, and all tests that were passing before my changes are still passing.
