### ISSUE TITLE
Tags in extension repos

### ISSUE THREAD

**Issue by JasonFengJ9** [ibmruntimes/openj9-openjdk-jdk#345]
Just noticed that there are some strange tag number difference among extension repos.

https://github.com/ibmruntimes/openj9-openjdk-jdk8 - 104 tags
https://github.com/ibmruntimes/openj9-openjdk-jdk11 - 642 tags
https://github.com/ibmruntimes/openj9-openjdk-jdk16 - 1361 tags
https://github.com/ibmruntimes/openj9-openjdk-jdk17 - 717 tags
https://github.com/ibmruntimes/openj9-openjdk-jdk - 1385 tags

`JDK17` has much less number of tags than `JDK` head and `JDK16` which is strange.
Also noticed that `JDK16` & `JDK` have many `hg-jdk-*` tags which shouldn't in these repos, these extra tags probably are the reason why `JDK16` has more tags than `JDK17`.

fyi @AdamBrousseau @pshipton @keithc-ca

**Comment by keithc-ca** [comment]
I used `git tag -l` to list all the tags from all those repos. I see nothing to be concerned about. The only ones we care about are those that relate to the primary version of the repo (e.g. jdk8u* in jdk8), and since the introduction of `openjdk-tag.gmk` we don't even need those. As noted, most of the excess tags in jdk16 are name hg-jdk* which we never needed.
