### ISSUE TITLE
Copyright checker failing on generated-configure.sh

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk#57]
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/210
https://ci.eclipse.org/openj9/job/PullRequest-CopyrightCheck-OpenJDK8/345/
```
14:11:32 The following files were modified and have incorrect copyrights
[Pipeline] echo
14:11:32 common/autoconf/generated-configure.sh
14:11:32 	IBM Copyright (basic) is missing from the file
[Pipeline] echo
14:11:32 jdk/make/closed/autoconf/generated-configure.sh
14:11:32 	IBM Copyright (basic) is missing from the file
```

there are IBM copyrights, but not in the first 100 lines.

**Comment by pshipton** [comment]
@groeges

**Comment by groeges** [comment]
OK, will take a look.

**Comment by groeges** [comment]
Discussed with Andrew and determined that as this is only a build file and is generated from .m4 files etc and not part of the JDK image we don't need to check the copyrights on these files. Have added the generated-configure.sh files to the .copyrightignore file.
PR for this issue is: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/220
